version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=udemy_learn_user
      - POSTGRES_PASSWORD=udemy_learn_password
      - POSTGRES_DB=udemy_learn_db
    networks:
      - udemy-learn-container
    ports:
      - "5432:5432"

volumes:
  postgres_data:


networks:
  udemy-learn-container:
