# このワークフローは、mainブランチへのpushやpull requestが発生したときに実行されます
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Ubuntuの最新バージョンでジョブを実行

    steps:
      - uses: actions/checkout@v2
        # コードをGitHubリポジトリからチェックアウト（取得）します

      - name: Install dependencies
        # todo-appディレクトリに移動し、npmで依存パッケージをインストール
        run: cd todo-app && npm install

      - name: Run Jest tests
        # Jestでテストを実行
        run: cd todo-app && npm test

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        # Azureにログイン（認証情報はGitHubのシークレットから取得）

      - name: Build and Push to ACR

        # Azure Container Registry(ACR)にログイン
        # todo-appのDockerイメージをビルドし、タグを付ける
        # ビルドしたイメージをACRにプッシュ
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/todo-app:${{ github.sha }} ./todo-app
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/todo-app:${{ github.sha }}

      - name: Deploy to Azure App Service
        # Azure App Serviceに、ACRのDockerイメージをデプロイ
        run: |
          az webapp config container set \
            --name udemytodoapp-app \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ secrets.ACR_NAME }}.azurecr.io/todo-app:${{ github.sha }}